name: Develop Tag
run-name: ${{ github.actor }} is publishing the image for homol
on:
  push:
    branches:
      - develop
    tags:
      -  'v*'

jobs:
  Publish-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: otavioabreu27/python_cicd
        
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{github.workspace}}
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}/develop
          labels: ${{ steps.meta.outputs.labels }}
